export enum PathName {
  SignIn = '/sign-in',
  SignUp = '/sign-up',
  StorageSetup = '/storage-setup',
  CreateFamily = '/create-family',
  Statistics = '/statistics',
  Storage = '/storage',
  ShoppingList = '/shopping-list',
  UserProfile = '/profile',
  Family = '/profile/family',
  Invitations = '/profile/invitations',
  PersonalInformation = '/profile/personal-info',
  ChangePassword = '/profile/change-password',
  InviteMembers = '/invite-members',
  QuitFamily = '/quit-family',
  Recipes = '/recipes',
  NewProduct = '/new-product',
  CustomProduct = '/custom-product',
  OnboardingTrackWaste = '/onboarding/track-waste',
  OnboardingMakeLists = '/onboarding/make-lists',
  OnboardingInviteMembers = '/onboarding/invite-members',
  ForgotPassword = '/forgot-password',
  EmailSentScreen = '/email-sent'
}
