name: PR Checks
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint:no-fix
      - name: Lint functions folder
        run: cd ./functions && npm run lint
      - name: Build
        run: npm run build
      # - name: Run E2E tests
      #   uses: cypress-io/github-action@v1
      #   with:
      #     command: npm test
      #     start: npm start
      #     wait-on: 'http://localhost:8080'
      #   env: 
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      #     VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
      #     VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN }}
      #     VUE_APP_PROJECT_ID: ${{ secrets.VUE_APP_PROJECT_ID }}
      #     VUE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_STORAGE_BUCKET }}
      #     VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}
      #     VUE_APP_APP_ID: ${{ secrets.VUE_APP_APP_ID }}
      #     VUE_APP_MEASUREMENT_ID: ${{ secrets.VUE_APP_MEASUREMENT_ID }}
