name: PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and lint
        uses: actions/checkout@v2
        run: npm i && npm run lint:no-fix
      - name: Build
        run: npm run build
    
