name: PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies and lint
        run: npm i && npm run lint:no-fix
      - name: Build
        run: npm run build
      - name: Run E2E tests
        uses: cypress-io/github-action@v1
        with:
          start: npm run emulate, npm run serve-dev
          command: npm run test
          wait-on: 'http://localhost:8080'
