name: PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      # - name: Lint
      #   run: npm run lint:no-fix
      # - name: Build
      #   run: npm run build
      - name: Run server & emulators
        run: |
          npm run emulate &
          npm run serve-dev &
      - name: Check the server is running
        uses: smurfpandey/wait-for-it@v1.0
        with:
          host: http://localhost
          port: 8080
          timeout: 60
      - name: Check the emulators are running
        uses: smurfpandey/wait-for-it@v1.0
        with:
          host: http://localhost
          port: 4000
          timeout: 60
      - name: Run E2E tests
        uses: cypress-io/github-action@v1
        with:
          command: npm test
          wait-on: 'http://localhost:8080'
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
